### ISSUE TITLE
Great project!

### ISSUE THREAD

**Issue by orthoxerox** [fglaeser/mqinetlite#1]
I've *just* been thinking of starting something like that, and *bam*, there's your NuGet package right there, just hours old. Can't wait to try it out. Do you plan to implement the XMS object model?

**Comment by fglaeser** [comment]
Hi @orthoxerox  thanks for your comments. As you can see, there still some missing verbs like MQSUB, that is my first priority. To be honest with you, the XMS object model is not something that we are currently using. Perhaps in the future, maybe you can contribute with that, what do you think?

**Comment by orthoxerox** [comment]
I'll see what I can do. XMS is not a priority for us either. I think I'll start with async methods first.
