### ISSUE TITLE
Licence details not found

### ISSUE THREAD

**Issue by shabeer-thazhathethil** [fglaeser/mqinetlite#2]
Please add the license details

**Comment by orthoxerox** [comment]
@tshabeer The latest redistributable client from IBM (9.1.1.0) contains a .Net Standard lib that runs fine in thin mode on both Linux and Windows.

**Comment by fglaeser** [comment]
@orthoxerox Good to know. I'll check that.

**Comment by fglaeser** [comment]
@orthoxerox Could you tell me the name of the dll ? I've just downloaded this 9.1.1.0-IBM-MQC-Redist-Win64.zip

**Comment by orthoxerox** [comment]
@fglaeser amqmdnetstd.dll plus amqmxmsstd.dll for XMS

https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.1.0/com.ibm.mq.dev.doc/q132490_.htm
