### ISSUE TITLE
how publish linux?

### ISSUE THREAD

**Issue by zhuxianchen** [fglaeser/mqinetlite#3]
Unable to load shared library 'mqic' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libmqic: cannot open shared object file: No such file or directory

**Comment by fglaeser** [comment]
Hi, first of all, You need to download the 8.0.0.10-WS-MQC-Redist-LinuxX64, then You need to run the command genmqpkg (Inside the bin folder), this command will generate a reduce package. After that yo can copy the folder in /opt/mq. Then you can run something like this to register the path with ldconfig command.

```
echo "/opt/mq/lib64" > /etc/ld.so.conf.d/mq.conf
ldconfig
 ```
