### ISSUE TITLE
Test case execution failed

### ISSUE THREAD

**Issue by flopgiggle** [fglaeser/mqinetlite#4]
I ran the test cases, but I encountered the following problems：

Unable to load DLL 'mqic' or one of its dependencies

How can I solve it？

![image](https://user-images.githubusercontent.com/6229140/88903243-f4564800-d285-11ea-9dc7-7876e3be5cb8.png)
![image](https://user-images.githubusercontent.com/6229140/88903256-f91afc00-d285-11ea-88ed-cf1e78821e0c.png)

**Comment by fglaeser** [comment]
Hi, if you need to connect to IBM MQ, I recommend you to use this [package]( https://www.nuget.org/packages/IBMMQDotnetClient/) . mmqinet is no longer maintained, the lib was created to fill a gap when there was not a official netcore lib to connect to IBM MQ. Anyway if you one to play with it, you must  install de IBM MQ Client, you can check the prerequisite [here](https://github.com/fglaeser/mmqinet#installation).

Best Regards.
